### PR TITLE
Remove calls to the N3 library

### PR DESCRIPTION
**Pull request by aaron-collier**
## Why was this change made?

~Currently, the data returned from mongo is not supported by the N3 library resulting in empty data sets when serializing into turtle or n3.~

Opening this PR as DRAFT in order to open discussion. Do we still want/need to support N3/turtle serialization.

## How was this change tested?

N/A - though removing this library will inherently increase test coverage (winning!)

## Which documentation and/or configurations were updated?

N/A

### CODE REVIEW

**Comment by justinlittman** [comment]
Can you say more about "the data returned from mongo is not supported by the N3 library"?

**Comment by aaron-collier** [comment]
@justinlittman actually, that was a bad assumption. I wasn't using the right properly on the resource, so I've updated my comment. Still curious if we need to support this.

**Comment by justinlittman** [comment]
So there are not direct requirements for supporting these formats. However, they provide a facade of linked data goodness and are potentially useful for integrating with external systems.

**Comment by aaron-collier** [comment]
Closing for now. It may be something to revisit later.

**Pull request closed without merging**
